title: CSC 374 Lab Assignments
description: CSC 374 Lab Assignments

baseurl: "/csc-374-docs"

remote_theme: JV-conseil/jekyll-theme-read-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown