title: CSC 374 Lab Assignment 0
description: Basics of Shell and Basics of C

baseurl: "/csc-374"

remote_theme: JV-conseil/jekyll-theme-read-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown